# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'soundwise_v2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for soundwise_v2
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

  pod 'FBSDKCoreKit'  
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'
  pod 'FBSDKMessengerShareKit'
  
  
  pod 'Fabric'
  pod 'Crashlytics'

  target 'soundwise_v2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

